# Welcome to Jekyll!

# Website settings
title: "Kuek Kiang Kuang"
description: "Kiang Kuang's portfolio"
keywords: "Kiang Kuang,java,php,c#,javascript"
baseurl: "/"
url: "https://kiangkuang.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Kuek Kiang Kuang'
  first_name: 'Kiang Kuang'
  last_name: 'Kuek'
  email: 'kiangkuang@gmail.com'
  facebook_username: 'kiangkuang'
  github_username: 'kiangkuang'
  linkedin: 'kiangkuang'
  head_img: 'static/img/landing/photo.jpg'
  desc: '
  <p>
    I am excited to explore the world of web development in a commercial environment, to put what I have learnt and what I can learn to the test.
  </p>
  <p>
    I am a graduate of NUS with <b>Bachelor of Computing (Honours) in Computer Science</b> with the focus area of <b>Interactive Media</b> and <b>Visual Computing</b>.
  </p>
  <p>
    I am experienced in front-end development languages such as <b>HTML</b>, <b>CSS</b>, <b>JavaScript</b>, back-end development languages such as <b>PHP</b>, <b>MySQL</b>, and general purpose programming languages such as <b>Java</b> and <b>C</b>.
    I am also equipped with complementary skills of design and experience in Human Computer Interaction.
  </p>
  <p>
    My past experiences include a 6-month internship as a web developer in <b>ShopBack</b> and a 3-month internship as a software engineer in <b>Animagine Pte Ltd</b> and various leadership positions.
  </p>
  '

# sections
sections:
  - id: 'about-me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'contact'
    name: 'Contact'
    tpl: 'contact.html'
    css: 'contact'

# # google analytics
# ga:
#   id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
